# Hello Word

In [2]:
print("Hello world!")

Hello world!


In [3]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.6 MB 18.0 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.6 MB 15.0 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 15.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 16.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 14.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [4]:
%pip install sympy

   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ------ --------------------------------- 1.0/6.3 MB 10.1 MB/s eta 0:00:01
   ---------------------------- ----------- 4.5/6.3 MB 13.7 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 12.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   --------------------------------------- 536.2/536.2 kB 10.6 MB/s eta 0:00:00

   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- -----------------

In [5]:
%pip install matplotlib

   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.1 MB 4.1 MB/s eta 0:00:02
   --------- ------------------------------ 1.8/8.1 MB 4.6 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.1 MB 5.0 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 5.4 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.1 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 6.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   --------------------------------- ------ 1.8/2.2 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 7.7 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------  2.6/2.7 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 10.9 MB/s eta 0:00:00

   ----- ---------------------

In [6]:
%pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.5 MB 8.6 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.5 MB 7.6 MB/s eta 0:00:02
   ---------------- ----------------------- 4.7/11.5 MB 8.5 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.5 MB 9.3 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 10.0 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 10.0 MB/s eta 0:00:00

   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------

In [7]:
%pip install scipy

   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
    --------------------------------------- 0.5/41.0 MB 2.6 MB/s eta 0:00:16
   - -------------------------------------- 1.3/41.0 MB 3.7 MB/s eta 0:00:11
   -- ------------------------------------- 2.4/41.0 MB 4.4 MB/s eta 0:00:09
   --- ------------------------------------ 3.9/41.0 MB 5.2 MB/s eta 0:00:08
   ----- ---------------------------------- 5.5/41.0 MB 5.6 MB/s eta 0:00:07
   ------- -------------------------------- 7.3/41.0 MB 6.1 MB/s eta 0:00:06
   --------- ------------------------------ 9.4/41.0 MB 6.8 MB/s eta 0:00:05
   ----------- ---------------------------- 12.1/41.0 MB 7.6 MB/s eta 0:00:04
   -------------- ------------------------- 14.7/41.0 MB 8.2 MB/s eta 0:00:04
   ---------------- ----------------------- 16.5/41.0 MB 8.3 MB/s eta 0:00:03
   ------------------ --------------------- 19.4/41.0 MB 8.7 MB/s eta 0:00:03
   ----------------------- ---------------- 24.1/41.0 MB 9.9 MB/s eta 0:00:02
 

In [8]:
%pip install yfinance

     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     --- ------------------------------------ 0.3/3.0 MB ? eta -:--:--
     ------------- -------------------------- 1.0/3.0 MB 3.3 MB/s eta 0:00:01
     ------------------------ --------------- 1.8/3.0 MB 3.7 MB/s eta 0:00:01
     ---------------------------------------- 3.0/3.0 MB 4.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
  Using cached certifi-2025.4.26-py3-none-any.whl.metadata (2.5 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   --------------------

In [9]:
%pip install scikit-learn

   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 1.5 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/11.1 MB 2.3 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/11.1 MB 1.9 MB/s eta 0:00:06
   ----- ---------------------------------- 1.6/11.1 MB 1.6 MB/s eta 0:00:06
   ------ --------------------------------- 1.8/11.1 MB 1.5 MB/s eta 0:00:06
   ------- -------------------------------- 2.1/11.1 MB 1.7 MB/s eta 0:00:06
   --------- ------------------------------ 2.6/11.1 MB 1.7 MB/s eta 0:00:05
   ------------ --------------------------- 3.4/11.1 MB 1.9 MB/s eta 0:00:04
   --------------- ------------------------ 4.2/11.1 MB 2.1 MB/s eta 0:00:04
   ----------------- ---------------------- 5.0/11.1 MB 2.4 MB/s eta 0:00:03
   -----------------

In [11]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt
import pandas as pd
import scipy.optimize as opt
import yfinance as yf
from sklearn.preprocessing import StandardScaler
print("Todas las librerías están instaladas correctamente.")

Todas las librerías están instaladas correctamente.


In [12]:
import numpy as np
# Crear un array y calcular su suma
array = np.array([1, 2, 3, 4, 5])
print("Array:", array)
print("Suma del array:", np.sum(array))

Array: [1 2 3 4 5]
Suma del array: 15


In [13]:
import sympy as sym
# Definir una variable simbólica y calcular la derivada
x = sym.Symbol('x')
func = x**2 + 3*x + 2
derivada = sym.diff(func, x)
print("Función:", func)
print("Derivada:", derivada)

Función: x**2 + 3*x + 2
Derivada: 2*x + 3


In [ ]:
import matplotlib.pyplot as plt
# Crear un gráfico simple
x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]
plt.plot(x, y, marker='o')
plt.title("Gráfico de x vs y")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.show()

In [14]:
import pandas as pd
# Crear un DataFrame y realizar operaciones básicas
data = {'Nombre': ['Ana', 'Luis', 'María'], 'Edad': [25, 30, 22]}
df = pd.DataFrame(data)
print("DataFrame:")
print(df)
print("\nEdades promedio:", df['Edad'].mean())

DataFrame:
  Nombre  Edad
0    Ana    25
1   Luis    30
2  María    22

Edades promedio: 25.666666666666668


In [16]:
import scipy.optimize as opt
# Encontrar el mínimo de una función cuadrática
def f(x):
    return x**2 + 3*x + 2
resultado = opt.minimize(f, x0=0)  # x0 es el punto inicial
print("Punto mínimo:", resultado.x)

Punto mínimo: [-1.50000001]


In [17]:
import time
# Medir cuánto tiempo tarda un bucle
start_time = time.time()
for i in range(1000000):
   pass
end_time = time.time()
print("Tiempo de ejecución:", end_time - start_time, "segundos")

Tiempo de ejecución: 0.02492070198059082 segundos


In [18]:
import yfinance as yf
# Descargar datos históricos de una acción
apple = yf.Ticker("AAPL")
hist = apple.history(period="5d")  # Últimos 5 días
print("Datos históricos de AAPL:")
print(hist)

Datos históricos de AAPL:
                                 Open        High         Low       Close  \
Date                                                                        
2025-05-19 00:00:00-04:00  207.910004  209.479996  204.259995  208.779999   
2025-05-20 00:00:00-04:00  207.669998  208.470001  205.029999  206.860001   
2025-05-21 00:00:00-04:00  205.169998  207.039993  200.710007  202.089996   
2025-05-22 00:00:00-04:00  200.710007  202.750000  199.699997  201.360001   
2025-05-23 00:00:00-04:00  193.669998  197.699997  193.460007  195.270004   

                             Volume  Dividends  Stock Splits  
Date                                                          
2025-05-19 00:00:00-04:00  46140500        0.0           0.0  
2025-05-20 00:00:00-04:00  42496600        0.0           0.0  
2025-05-21 00:00:00-04:00  59211800        0.0           0.0  
2025-05-22 00:00:00-04:00  46742400        0.0           0.0  
2025-05-23 00:00:00-04:00  78314800        0.0          

In [19]:
from sklearn.preprocessing import StandardScaler
import numpy as np
# Escalar datos
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print("Datos originales:")
print(data)
print("\nDatos escalados:")
print(scaled_data)

Datos originales:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Datos escalados:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
